# ========== 字体配置（松山拓也常用 Nerd 等宽字体） ==========
font_family      JetBrainsMonoNL Nerd Font Mono
font_size        13.0
bold_font        auto
italic_font      auto
bold_italic_font auto
box_drawing_chars use builtin

# 恢复正常窗口（可移动、可最大化、有标题栏）
window_decorations            full
hide_window_decorations       no
enable_ime                    yes
single_window_margin_width    10

enable_ime yes
ime_use_simple_preedit no
gtk_im_module fcitx
qt_im_module fcitx
##光标动画
cursor_trail 3



