# ========== 窗口基础尺寸与边框UI设置 ==========
term xterm-kitty

remember_window_size yes
initial_window_width  1200
initial_window_height 800
window_padding_width  10

# active_border_color   #89dceb
# inactive_border_color #45475a
border_width 1
startup_mode fullscreen

#hide_window_decorations no
#window_decorations full

# 隐藏所有窗口装饰
window_decorations full
hide_window_decorations no
# 保留退出全屏的快捷键
map F11 toggle_fullscreen

