# ========== 窗口基础尺寸与边框UI设置 ==========
term xterm-kitty

remember_window_size yes
initial_window_width  1200
initial_window_height 800
window_padding_width  10

# active_border_color   #89dceb
# inactive_border_color #45475a
border_width 1

hide_window_decorations yes
