# ========== 全局修饰键（兼容Tmux生态） ==========
kitty_mod ctrl+shift

# ========== 自定义快捷键 ==========
map kitty_mod+r reload_config

# ========== 打开主题选择界面 ==========
map kitty_mod+t kitten themes

# ========== 新建/关闭窗口 ==========
map kitty_mod+enter new_window
map kitty_mod+q close_window

# ========== 窗口分屏（和 Tmux 逻辑对齐） ==========
map kitty_mod+d split_window right
map kitty_mod+s split_window down

# ========== 窗口标签切换 ==========
map kitty_mod+left  previous_window
map kitty_mod+right next_window

# ========== 全局字体大小调节 ==========
map kitty_mod+equal    change_font_size all +1.0
map kitty_mod+minus     change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0

