# ========== 颜色主题引入 ==========
include themes/tokyonight.conf

# ========== 自定义高亮色覆写 ==========
color2  #9ece6a
color10 #9ece6a

# ========== 背景透明+模糊 ==========
background_opacity 0.8
background_blur 50

# ========== 当前生效主题软链接 ==========
include current-theme.conf



